### ISSUE TITLE
Bee drones disappear on multiplayer server.

### ISSUE THREAD

**Issue by ShibeTemple** [HexagonNico/BuzzyDrones#3] opened 2022-01-04 11:40 UTC
Hello :)

My bee drones despawn on my server. There is no possibility of mobs or players killing them, and I am unsure of what to do. The mod is practically useless if the drones despawn which sucks because I love this mod. I was so excited to make bee drones and everything. Such a shame that they disappear.

This issue is reproducible, however over a long period of time (1-2 real days).

I have also seen other people mention this issue on the CurseForge page (Ex, bobbobb3746, and nadiachair).

Let me know how I can help with this issue.

Server: 1.16.5 Forge 36.2.20

**Comment by HexagonNico** [comment] 2022-01-07 09:38
Version 2.0.1 has been uploaded to CurseForge which should have hopefully fixed the problem. However, since it is hard to reproduce I'm not closing this issue yet in case it might still happen in the new version.

**Comment by ShibeTemple** [comment] 2022-01-18 05:05
Hello, bees are still disappearing. This time it did not happen overnight, but only in a few (maybe 3-4) hour session. This is on version 2.0.1. The bee was named as well.

**Comment by HexagonNico** [comment] 2022-01-18 09:30
I finally found the solution. Drones were despawning when there was no player close to them, same as other mobs do.
So I found this:
```
    @Override
    public boolean removeWhenFarAway(double d) {
        return false;
    }
```

I noticed this method returned `true` by default for living entities, but it was changed to `false` for the iron golem and the snow golem.

I tried placing down a drone and teleporting myself 10k blocks away, when I teleported myself back the drone was still there. Then I tried the same thing after I commented out the code and this time the drone was gone.

Thank you for pointing me in the right direction, I'm glad this bug is finally solved.

**Closed as completed by HexagonNico** 2022-01-18 09:30 UTC
Labels: Bug
